# Generated by Django 4.1 on 2022-09-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('date_created', models.DateField(auto_created=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=400)),
            ],
        ),
    ]
